### ISSUE TITLE
Any instructions on implementing?

### ISSUE THREAD

**Issue by dimadobriy** [asalimil/Nonlinear-MPC-for-collision-free-and-deadlock-free-navigation-of-multiple-nonholonomic-mobile-robots#1]
Hi @asalimil!

First of all thanks for sharing the code. I really enjoyed published paper and this project.

I'm trying to reproduce your results. Could you provide some running instructions please?

I'm trying to execute scripts in the directory ```AllScripts```, however, it results different errors:
e.g. running script ```obs_avoid_static_first_scenario.py``` results in
```Traceback (most recent call last):
  File "obs_avoid_static_first_scenario.py", line 185, in <module>
    f2_value = f2(a,st,st_next,con)
NameError: name 'f2' is not defined
```

What version of ROS and Python are you using?

Thanks a lot!

Best regads

**Comment by asalimil** [comment]
Hi @dimadobriy,
Sorry for the issue and I appreciate that you reached out to me. 
Let's start with uncommenting **Line #111**. 
I might have commented out the line that defines the f2 function.
Please let me if that resolves the error and feel free to contact me at **asalimil@asu.edu** if you have any further questions or have any issues with running the code.
Best, 
Amir

**Comment by dimadobriy** [comment]
Hi @asalimil,
Thanks for your answer. After uncommenting **Line #111** I've got

```Traceback (most recent call last):
  File "/home/dima/.local/lib/python3.8/site-packages/casadi/casadi.py", line 9209, in __array__
    return self.full()
  File "/home/dima/.local/lib/python3.8/site-packages/casadi/casadi.py", line 7977, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, SX, name)
  File "/home/dima/.local/lib/python3.8/site-packages/casadi/casadi.py", line 83, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'SX' object has no attribute 'full'

During handling of the above exception, another exception occurred:

```Traceback (most recent call last):
  File "obs_avoid_static_first_scenario.py", line 68, in <module>
    states = np.array([[x], [y], [theta]]); n_states = len(states)
  File "/home/dima/.local/lib/python3.8/site-packages/casadi/casadi.py", line 9211, in __array__
    raise Exception("Implicit conversion of symbolic CasADi type to numeric matrix not supported.\n"
Exception: Implicit conversion of symbolic CasADi type to numeric matrix not supported.
This may occur when you pass a CasADi object to a numpy function.
Use an equivalent CasADi function instead of that numpy function
```

Probably we use different ver of Python/ROS? However, Casadi seems fails...

UPD: Well, I have downgraded the **numpy** ver to 1.18 and the error above disappear.  However, I got another one :)

```Traceback (most recent call last):
  File "obs_avoid_static_first_scenario.py", line 185, in <module>
    f2_value = f2(a,st,st_next,con)
  File "/home/dima/.local/lib/python3.8/site-packages/casadi/casadi.py", line 13444, in __call__
    ret = self.call(args)
  File "/home/dima/.local/lib/python3.8/site-packages/casadi/casadi.py", line 12324, in call
    return _casadi.Function_call(self, *args)
RuntimeError: .../casadi/core/function_internal.hpp:1241: Assertion "arg.size()==n_in_" failed:
Incorrect number of inputs: Expected 2, got 4
```

Best regards,
Dmitrii

**Comment by asalimil** [comment]
Hi @dimadobriy,
I used ROS Kinetic + Gazebo 9 + Python 2.7 on Ubuntu 16. 
Please also make sure you install the compatible version of CasaDi with the ROS and Python versions. 
-- Amir

**Comment by dimadobriy** [comment]
Hi @asalimil,
I use ROS Noetic+ Gazebo 11 + Python 3.8 on Ubuntu 20.04. 

I think that could cause the errors above.

However I could execute script ```python3 centralized_one_robots_implementation.py``` and it works :) 

I will try another scenarios under your setup. I think the issue could be closed. 

Thanks a lot!

-- Dmitrii

**Comment by asalimil** [comment]
Hi Dmitrii,
Awesome, I am glad that worked.
Those python files whose name ends with "implementation" are those codes
that I implemented on actual TB3. Other codes have been used in Gazebo
simulations.
I hope that helps.
Best regards,
-- Amir
